"""Initial database schema

Revision ID: a04905a58657
Revises: 
Create Date: 2026-07-22 08:16:09.909744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04905a58657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('colorway', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column(
    'currency',
    sa.String(length=3),
    nullable=False,
    server_default='USD'
),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column(
    'is_active',
    sa.Boolean(),
    nullable=False,
    server_default=sa.true()
),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sneakers_brand'), 'sneakers', ['brand'], unique=False)
    op.create_index(op.f('ix_sneakers_sku'), 'sneakers', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sneakers_sku'), table_name='sneakers')
    op.drop_index(op.f('ix_sneakers_brand'), table_name='sneakers')
    op.drop_table('sneakers')
    # ### end Alembic commands ###
